'use client'
import { motion } from 'motion/react'
import { SOCIAL_LINKS, EMAIL } from './data'

const sections = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } }
const PAPER_LINKS: Record<string,string> = {
 'CoPA：Benchmarking Personalized Question Answering with Data-Informed Cognitive Factors':'https://arxiv.org/abs/2604.14773',
 'Personalized Question Answering with User Profile Generation and Compression':'https://aclanthology.org/2025.findings-emnlp.255/',
 'Deep Knowledge Tracing with Learning Curves':'https://doi.org/10.3389/fpsyg.2023.1150329',
 'MDJOSC: matching digital talents and job titles in open source communities':'https://doi.org/10.1007/s11704-025-50084-x',
 'Knowledge Distillation for Job Title Prediction and Project Recommendation in Open Source Communities':'https://ecmlpkdd-storage.s3.eu-central-1.amazonaws.com/preprints/2025/ads/preprint_ecml_pkdd_2025_ads_623.pdf',
}
const internships = [
 { company:'上海合合信息科技股份有限公司（扫描全能王）', role:'大模型算法工程师', date:'2024.05 — 2024.11', intro:'面向 textin 智能文档抽取场景，负责多模态大模型部署、评测数据构建与效果分析。', bullets:['使用 lmdeploy 部署 InternVL2、LLaVA 等模型，通过 FastAPI 与 Docker 封装统一推理服务。','按抽取字段构建约 2500 条评测数据，覆盖发票、表格、证件等复杂版面。','基于 LangChain 开发多模态大模型评估 Agent Pipeline，将结果结构化为 JSON。','完成 badcase 分析、数据回流，为模型优化、Prompt 调整和复测提供依据。']},
 { company:'上海芯擎科技有限公司（ARM 子公司）', role:'AI 工具链开发工程师', date:'2023.06 — 2023.12', intro:'面向 NPU 平台的模型评测与工具链开发，支持跨平台精度验证和资源分析。', bullets:['使用 Python 开发跨平台模型评测 Pipeline，统一封装新思 EV 与周易平台接口。','对比模型输出张量与 gold data，自动计算准确率、误差并收集内存占用。','使用 Docker 封装不同平台运行依赖，生成统一格式的汇总表格与日志。']},
]
const research = [
 {title:'PersonaFactor：Fundamental Preference Factors for Multi-Scenario LLM Personalization', tag:'ICLR 2027（在投）｜第一作者', text:'针对个性化方法依赖表层历史、难以复用跨场景稳定偏好的问题，主导可解释的用户偏好因素建模。', bullets:['从 14 个任务子集的 66,018 条样本提取 186,253 条个性化理由，归纳认知、情境、身份、行为四维 13 类 PersonaFactors。','联合任务相关性与生成影响信号，设计动态因素选择组合机制，无需更新底层参数。','在 4 个基准和 4 个骨干模型上评测；Qwen3-8B 上 LongLaMP ROUGE-L 从 0.1437 提升至 0.1859（+29.4%）。','低维表示分析显示用户历史与 PersonaFactor 具有稳定共享结构并保留互补个性化信号。']},
 {title:'CoPA：Benchmarking Personalized Question Answering with Data-Informed Cognitive Factors', tag:'ACL 2026 Findings｜第一作者', text:'研究大模型对用户知识水平、认知偏好和表达方式差异的建模能力。', bullets:['分析约 680 万条 StackExchange 数据，整理 15,963 名用户、626,786 个问题，定义 CIPD 现象。','提取个性化决策理由，挖掘六类认知因素，构建 CoPA 个性化问答评测基准。','科学领域采纳答案识别准确率由 CoT 的 31.35% 提升至 53.44%，并在两个外部基准验证泛化。']},
 {title:'Personalized Question Answering with User Profile Generation and Compression', tag:'EMNLP 2025 Findings｜第一作者', text:'主导用户画像生成、持续更新与关键词压缩，降低冗余上下文开销。', bullets:['联合建模领域知识背景与跨领域全局画像，随提问持续更新以适配用户知识水平。','利用 Qwen2.5-72B 构建 6,732 对画像与关键词训练样本，训练 XLM-RoBERTa 压缩模型，提取关键背景信息以减少画像 token 开销。','基于信息论与 Zipf 定律，在优先移除低信息量词的假设下，推导压缩率与信息损失的近似关系，为适度压缩保留主要画像信息提供理论依据。','压缩画像在 Jaccard、IC 指标上均优于完整画像；在三个数据集、两个骨干模型上验证适度去除冗余信息能够改善个性化回答效果。']},
 {title:'Deep Knowledge Tracing with Learning Curves', tag:'Frontiers in Psychology｜共同第一作者', text:'研究显式融合学习曲线的知识状态预测方法。', bullets:['参与设计 CECAKT，以胶囊网络替代全局平均池化并融合 LSTM 整体知识状态。','在四个公开数据集上 AUC 最优或并列最优；ASSISTments2017 相比 CAKT 从 73.68% 提升至 74.41%。','通过消融、参数敏感性和知识状态可视化验证模型设计。']},
 {title:'编程训练的智能反馈与评价', tag:'国家自然科学基金子项目', text:'面向水杉在线教育平台，完成大模型部署、教学场景微调与后端推理服务。', bullets:['使用 GPT-4 构建指令数据，微调 DeepSeek-Coder-33B，引导学生思考而非直接给出答案。','在 A800 使用 vLLM 部署，结合 PagedAttention 与 Continuous Batching 支持高并发流式推理。','使用 ChromaDB 构建高质量问答库，并结合用户画像生成个性化教学回答。']},
]
export default function Personal(){return <motion.main className="space-y-20" initial="hidden" animate="visible" transition={{staggerChildren:.12}}>
 <motion.section variants={sections}><p className="text-zinc-600 dark:text-zinc-400">专注于大模型个性化、个性化问答与教育智能体研究，探索让 AI 更懂用户的技术。</p><p className="mt-4 text-sm text-zinc-500">数据科学与工程博士研究生 · 华东师范大学 × 北京中关村学院联合培养</p></motion.section>
 <motion.section variants={sections}><h3 className="mb-5 text-lg font-medium">教育经历</h3><div className="space-y-5 text-zinc-600 dark:text-zinc-400"><div><b className="text-zinc-900 dark:text-zinc-100">华东师范大学 × 北京中关村学院</b><span className="float-right text-sm">2021.09 — 至今</span><p>数据科学与工程｜博士研究生｜预计 2027 年底毕业</p><p className="mt-2">博士期间围绕大模型个性化与个性化教育智能体开展研究，重点关注用户认知建模、个性化问答与知识追踪。目前已以第一作者（含共同第一作者）完成论文 4 篇，其中 ICLR 2027 在投 1 篇、ACL 2026 录用 1 篇、EMNLP 2025 录用 1 篇、SSCI 一区期刊发表 1 篇。</p></div><div><b className="text-zinc-900 dark:text-zinc-100">南京师范大学</b><span className="float-right text-sm">2015.09 — 2019.07</span><p>能源与动力工程｜本科</p></div></div></motion.section>
 <motion.section id="experience" variants={sections}><h3 className="mb-5 text-lg font-medium">实习经历</h3><div className="space-y-8">{internships.map(x=><article key={x.company}><h4 className="font-medium">{x.role}<span className="float-right text-sm font-normal text-zinc-500">{x.date}</span></h4><p className="text-zinc-500">{x.company}</p><p className="mt-2 text-zinc-600 dark:text-zinc-400">{x.intro}</p><ul className="mt-2 list-disc space-y-1 pl-5 text-zinc-600 dark:text-zinc-400">{x.bullets.map(b=><li key={b}>{b}</li>)}</ul></article>)}</div></motion.section>
 <motion.section id="research" variants={sections}><h3 className="mb-5 text-lg font-medium">科研经历与代表成果</h3><div className="space-y-9">{research.map(x=><article key={x.title}><h4 className="font-medium leading-6">{PAPER_LINKS[x.title] ? <a className="underline decoration-zinc-300 underline-offset-4 hover:text-indigo-600" href={PAPER_LINKS[x.title]} target="_blank" rel="noreferrer">{x.title} ↗</a> : x.title}</h4><p className="text-sm text-indigo-600 dark:text-indigo-300">{x.tag}</p><p className="mt-2 text-zinc-600 dark:text-zinc-400">{x.text}</p><ul className="mt-2 list-disc space-y-1 pl-5 text-zinc-600 dark:text-zinc-400">{x.bullets.map(b=><li key={b}>{b}</li>)}</ul></article>)}</div></motion.section>
 <motion.section variants={sections}><h3 className="mb-5 text-lg font-medium">其他代表成果</h3><ul className="list-disc space-y-2 pl-5 text-zinc-600 dark:text-zinc-400"><li><a className="underline" href={PAPER_LINKS['MDJOSC: matching digital talents and job titles in open source communities']} target="_blank" rel="noreferrer">MDJOSC: Matching Digital Talents and Job Titles in Open Source Communities ↗</a>。<span className="text-sm text-indigo-600 dark:text-indigo-300"> Frontiers of Computer Science｜第二作者</span></li><li><a className="underline" href={PAPER_LINKS['Knowledge Distillation for Job Title Prediction and Project Recommendation in Open Source Communities']} target="_blank" rel="noreferrer">Knowledge Distillation for Job Title Prediction and Project Recommendation in Open Source Communities ↗</a>。<span className="text-sm text-indigo-600 dark:text-indigo-300"> ECML 2025｜第二作者</span></li></ul></motion.section>
 <motion.section variants={sections}><h3 className="mb-4 text-lg font-medium">联系我</h3><p className="text-zinc-600 dark:text-zinc-400">欢迎通过 <a className="underline" href={`mailto:${EMAIL}`}>{EMAIL}</a> 联系我。</p><div className="mt-4 flex gap-3">{SOCIAL_LINKS.map(x=><a className="rounded-full bg-zinc-100 px-3 py-1 text-sm dark:bg-zinc-800" key={x.label} href={x.link}>{x.label}</a>)}</div></motion.section>
 </motion.main>}
